# Generated by Django 3.1.3 on 2020-11-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='name',
            new_name='title',
        ),
    ]
