# Generated by Django 3.1.3 on 2020-11-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0002_auto_20201116_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='title',
            new_name='name',
        ),
    ]
