# Generated by Django 3.1.3 on 2020-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0003_auto_20201116_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='function',
            name='nickname',
        ),
        migrations.AddField(
            model_name='class',
            name='className',
            field=models.CharField(default=1, max_length=255, verbose_name='类名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='function',
            name='functionName',
            field=models.CharField(default='1', max_length=255, verbose_name='函数名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='昵称'),
        ),
    ]
