# Generated by Django 3.1.3 on 2020-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0004_auto_20201117_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='parameterName',
            field=models.CharField(default='1', max_length=255, verbose_name='参数名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='昵称'),
        ),
    ]
