# Generated by Django 3.1.3 on 2020-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0005_auto_20201118_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='type',
            field=models.CharField(default='str', max_length=255, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='1', max_length=255, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
