# Generated by Django 3.1.3 on 2020-11-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0006_auto_20201118_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='category',
            field=models.CharField(choices=[('input', '输入'), ('output', '输出'), ('parameter', '参数')], default='parameter', max_length=255),
        ),
    ]
