# Generated by Django 3.1.3 on 2020-11-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0007_parameter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='belongClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tree.class'),
        ),
    ]
