# Generated by Django 3.1.3 on 2020-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名')),
                ('describe', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('createdData', models.DateTimeField(auto_now_add=True)),
                ('updatedData', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
