# Generated by Django 3.1.3 on 2020-11-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20201119_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='节点id')),
                ('label', models.CharField(max_length=100, verbose_name='节点名')),
                ('size', models.CharField(max_length=200, verbose_name='节点尺寸')),
                ('type', models.CharField(max_length=100, verbose_name='节点类型')),
                ('x', models.IntegerField(verbose_name='节点x坐标')),
                ('y', models.IntegerField(verbose_name='节点y坐标')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
    ]
