# Generated by Django 3.1.3 on 2020-11-24 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0009_auto_20201124_2121'),
        ('Project', '0005_node_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='classes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tree.class'),
        ),
        migrations.AddField(
            model_name='node',
            name='fontSize',
            field=models.IntegerField(default=0, verbose_name='节点名字体大小'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='shape',
            field=models.CharField(default=0, max_length=100, verbose_name='节点形状'),
            preserve_default=False,
        ),
    ]
