# Generated by Django 3.1.3 on 2020-11-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20201124_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='节点id'),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.CharField(max_length=50, verbose_name='节点名'),
        ),
        migrations.AlterField(
            model_name='node',
            name='shape',
            field=models.CharField(max_length=50, verbose_name='节点形状'),
        ),
        migrations.AlterField(
            model_name='node',
            name='size',
            field=models.CharField(max_length=50, verbose_name='节点尺寸'),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(max_length=50, verbose_name='节点类型'),
        ),
    ]
