# Generated by Django 3.1.3 on 2020-11-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0009_auto_20201124_2121'),
        ('Project', '0007_auto_20201124_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tree.class'),
        ),
        migrations.AlterField(
            model_name='node',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tree.function'),
        ),
    ]
