# Generated by Django 3.1.3 on 2020-11-24 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_auto_20201124_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='节点id')),
                ('end', models.TextField(blank=True, null=True)),
                ('endPoint', models.TextField(blank=True, null=True)),
                ('endPointId', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('startPoint', models.TextField(blank=True, null=True)),
                ('startPointId', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('target', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=50, verbose_name='边类型')),
                ('shape', models.CharField(max_length=50, verbose_name='边形状')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.graph')),
                ('sourceNode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sourceNode', to='Project.node')),
                ('targetNode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='targetNode', to='Project.node')),
            ],
        ),
    ]
