# Generated by Django 3.1.3 on 2020-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='endPoint',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='endPointId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='start',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='startPoint',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='startPointId',
            field=models.CharField(max_length=50),
        ),
    ]
