# Generated by Django 3.1.3 on 2020-11-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0009_auto_20201124_2121'),
        ('Project', '0010_auto_20201126_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project.graph'),
        ),
        migrations.AlterField(
            model_name='node',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tree.class'),
        ),
        migrations.AlterField(
            model_name='node',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tree.function'),
        ),
        migrations.AlterField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project.graph'),
        ),
    ]
