# Generated by Django 3.1.3 on 2020-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_auto_20201126_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.CharField(max_length=50),
        ),
    ]
