# Generated by Django 3.1.3 on 2020-11-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_auto_20201130_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='valueType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='节点运行结果类型'),
        ),
    ]
